apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: cache-store-allow-ingress
  namespace: secure-middleware
spec:
  podSelector:
    matchLabels:
      app: cache-store
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: internal-proxy
      namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: default
    ports:
    - protocol: TCP
      port: 6379
